name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm install

    - name: Run linting
      run: npm run lint # Runs eslint to ensure code quality

  
    - name: Deploy to Staging
      if: success()
      run: |
        echo "Deploying to staging environment..."
        # Insert your actual deployment commands here
